#ddev-generated
# Install cron package; this can be done in webimage_extra_packages, but put it here for now.
RUN (apt-get update || true) && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" \
  --no-install-recommends --no-install-suggests ansible
